<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLGjkBrZ\srcAtom3_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLGjkBrZ/srcAtom3_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLGjkBrZ.legacy');

    return;
}

if (!\class_exists(srcAtom3_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLGjkBrZ\srcAtom3_KernelDevDebugContainer::class, srcAtom3_KernelDevDebugContainer::class, false);
}

return new \ContainerLGjkBrZ\srcAtom3_KernelDevDebugContainer(array(
    'container.build_hash' => 'LGjkBrZ',
    'container.build_id' => 'e58bde7a',
    'container.build_time' => 1544565622,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLGjkBrZ');
