<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLDf2x1T\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLDf2x1T/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLDf2x1T.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLDf2x1T\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLDf2x1T\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'LDf2x1T',
    'container.build_id' => '24e9af9a',
    'container.build_time' => 1544468670,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLDf2x1T');
