<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfpiz1U\srcAtom3_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfpiz1U/srcAtom3_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKfpiz1U.legacy');

    return;
}

if (!\class_exists(srcAtom3_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKfpiz1U\srcAtom3_KernelDevDebugContainer::class, srcAtom3_KernelDevDebugContainer::class, false);
}

return new \ContainerKfpiz1U\srcAtom3_KernelDevDebugContainer(array(
    'container.build_hash' => 'Kfpiz1U',
    'container.build_id' => 'c0528873',
    'container.build_time' => 1544498451,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfpiz1U');
